### ISSUE TITLE
design format changed after validation 

### ISSUE THREAD

**Issue by bishal-weavers** [timothyjensen/gravityformsadvancedselect#2]
here is the form page link - https://detroitgarage.wpengine.com/appointments/

when i submit the form , design of the multi select option is breaking.

**Comment by mishterk** [comment]
Howdy,

I just noticed this issue as well. It happens on AJAX validation, presumably because GForms is changing the UI and the plugin JS needs to be re-initialized. I've just worked around this using the following: 

```javascript
jQuery(document).on('gform_post_render', function(){
  if (typeof window.gravityformsadvancedselectInitializeTomSelect === "function") {
    window.gravityformsadvancedselectInitializeTomSelect();
  }
});
```

@timothyjensen, thanks for loading up a nice simple function for us to call :)

Will you bake this into the plugin?

**Comment by timothyjensen** [comment]
Thank you both for your feedback. I have implemented the fix provided by @mishterk with minor tweaks - let me know if you run into issues.
